# Generated by Django 6.0.7 on 2026-07-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'estados_cita',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tipos_genero',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_primero', models.CharField(max_length=150)),
                ('nombre_segundo', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telef_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_colegiado', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.tipodocumento')),
            ],
            options={
                'db_table': 'dentistas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_primero', models.CharField(max_length=150)),
                ('nombre_segundo', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('apellido_materno', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo_pers', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_corp', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telef_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.tipodocumento')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.tipogenero')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True, null=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinica.dentista')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.estadocita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.paciente')),
            ],
            options={
                'indexes': [models.Index(fields=['paciente'], name='clinica_cit_pacient_9bad09_idx'), models.Index(fields=['dentista'], name='clinica_cit_dentist_97eb73_idx'), models.Index(fields=['fecha_cita'], name='clinica_cit_fecha_c_b70ae5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dentista',
            index=models.Index(fields=['numero_documento'], name='dentistas_numero__1f9f96_idx'),
        ),
        migrations.AddIndex(
            model_name='dentista',
            index=models.Index(fields=['numero_colegiado'], name='dentistas_numero__91af53_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['numero_documento'], name='pacientes_numero__14d398_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['correo_pers'], name='pacientes_correo__e38376_idx'),
        ),
    ]
